name: Scrape Processos

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Atualizado para v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Atualizado para v3
        with:
          node-version: '20'  # Usando Node.js 20

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run scraper
        run: node scrape.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add processos.json
          git commit -m 'Update processos' || echo "No changes to commit"
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/tgszwdv/processos.git HEAD:main
